Adding some style to the project
Bigizi/LeaderBoard pull request #3
Opened 2023-02-09 14:44 UTC by Bigizi

**Leader-Board-Project**

I added some styles to the project in the style CSS file.

2023-02-09 15:15 UTC, bobb-Rob requested changes
## STATUS: CHANGES REQUIRED ♻️
Hi @Bigizi , 

Good job so far! 👏👏👏 
There are some issues that you still need to work on to go to the next project but you are almost there!  😃 
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>
![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)

## Highlights
✅ No Linter error
✅ Correct use of Gitflow
✅ Very descriptive Pull Request(PR)
✅ Neat Commit messages

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-09 15:15 UTC, bobb-Rob commented on dist/index.html
> +        <h1 id="h1">LeaderBoard</h1>
- [ ] Your README file does look professional to some level but needs to contain all that's needed for running the app with the API(s) it consumes. It should have instructions about how to clone, install, and any other details needed to run the app. This information should be provided knowing that both non-technical and technical users will use it.
- [ ] Please add license section of this README. Ensure when clicked, it take the user to the license page on github. 

You README.md **_Getting started section_**
![image](https://user-images.githubusercontent.com/84156714/217850496-1c14113a-bf41-4001-96b3-e6e61e28fbae.png)

Please edit this section showing how one can use this repo.

2023-02-09 15:46 UTC, GzimAsani requested changes
### Hello @Bigizi                         :wave:   
 Good job so far,  done There are some issues that you still need to work on to go to the next project but you are almost there!
 
 ## Highlights
 * Good job with adding some of the requirements asked previously :+1: 

 ## Required Changes 
- [ ] Check the comments below :arrow_double_down: 


 ## Optional suggestions
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding! clapclapclap
 
 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
 
 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-09 15:46 UTC, GzimAsani commented on README.md
> +This project is [MIT](./LICENSE) licensed.
- [ ] The MIT link is returning a 404 page, kindly update it 
![image](https://user-images.githubusercontent.com/62705947/217862872-feedfe02-87ee-4a1f-a3f5-b8dab553463d.png)

2023-02-09 15:46 UTC, GzimAsani commented on README.md
> +Install any code editor in your computer the follow the step above to clone the repository
- [ ] As asked by the previous reviewer please include on your readme file how a non-technical user can clone, install dependencies and run your project, include commands as well

2023-02-10 07:47 UTC, mikethreels approved these changes
Hi Crispin, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- linters are passing
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-10 07:55 UTC, merged